### ISSUE TITLE
replace bind_rows with rbindlist

### ISSUE THREAD

**Issue by datarichard** [mstr3336/pipetree#25]
https://github.com/mstr3336/pipetree/blob/215eb7a66dcd3d9edda0f1fe7be3e1f0d9ca547e/R/cache_access.R#L72

Is it possible to replace line 72:

`out <- dplyr::bind_rows(already_combined, out)` 

with:

`out <- data.table::rbindlist(list(already_combined, out))`

For speed and economy (https://stackoverflow.com/questions/15673550/why-is-rbindlist-better-than-rbind)

**Comment by mstr3336** [comment]
thanks @datarichard , if you'd like to fork & PR i'd be happy to merge this

**Comment by mstr3336** [comment]
Resolved by #26 @datarichard
